### ISSUE TITLE
Error fetching game data

### ISSUE THREAD

**Issue by Ghegghe** [CarrotRub/Fit-Launcher#23] opened 2024-10-15 20:26 UTC
in v1.0.2 and in v1.0.3 i encountered a problem fetching game data opening the program. with the new version now i can see the error popup that say:

Network failure: There was a network issue, unable to retrieve latest game data. (E01)

![image](https://github.com/user-attachments/assets/549def8d-201c-450c-9b8c-819855f341ae)

**Comment by CarrotRub** [comment] 2024-10-16 10:52
Some countries and ISP block fitgirl repacks website such as Italy.
Please use a VPN.
A better error message is being worked on.
This is a duplicate of #21.

**Closed by CarrotRub** 2024-10-16 10:52 UTC
