### ISSUE TITLE
Crash on startup (Windows)

### ISSUE THREAD

**Issue by devsheva** [CarrotRub/Fit-Launcher#4] opened 2024-08-31 11:19 UTC
I just downloaded the app on my Windows PC. As soon as I try to run the launcher, it closes immediately and no report from Windows Defender is given so i guess it's not an antivirus problem

**Comment by CarrotRub** [comment] 2024-08-31 11:35
Can you send your config and check if you have smartscreen because it seems to be removing some files that the app needs

**Comment by devsheva** [comment] 2024-08-31 11:49
Did you mean the Windows Defender config like this?

![image](https://github.com/user-attachments/assets/ff9426ac-1551-45b5-b0b0-b6e9136d7ec4)

I've already checked the app & browser control, nothing there is related to the launcher, they're old scans from May. Smartscreen is on but it hasn't detected anything related to launcher i guess

**Comment by CarrotRub** [comment] 2024-08-31 12:13
Try to put the app to private network and disable the in real time av just for the first run then re-enable it (It is dangerous to keep it disabled)

**Comment by devsheva** [comment] 2024-08-31 13:25
did it, still having the same behaviour

**Comment by carlossclaro** [comment] 2024-09-02 00:15
@devsheva, 

Can you try opening https://fitgirl-repacks.site/ in your web browser and report back if you're able to load the page?

**Comment by devsheva** [comment] 2024-09-02 07:07
@carlossclaro without VPN no, but once enabled yes

**Comment by carlossclaro** [comment] 2024-09-02 10:13
> @carlossclaro without VPN no, but once enabled yes

Can you check your local and roaming folders in %appdata% and let me know if there are any folders relating to fit launcher and if they contain files inside.

2. Are you able to turn on your VPN and run the app again?

Let us know if it goes through or if it still crashes.

**Comment by devsheva** [comment] 2024-09-02 18:44
@carlossclaro 

> 1. Can you check your local and roaming folders in %appdata% and let me know if there are any folders relating to fit launcher and if they contain files inside.

In local i see a `EBWebView` folder with other folders and some files.
![image](https://github.com/user-attachments/assets/9e888bcc-e396-4744-8694-9e9f61bc1906)

On Roaming nothing.


> 2. Are you able to turn on your VPN and run the app again?
I think the VPN was the problem,  cause I didn't enable it when trying to run the app. Now it works! 

P.S. I'm from Italy

**Comment by carlossclaro** [comment] 2024-09-02 18:51
> @carlossclaro
> 
> > 1. Can you check your local and roaming folders in %appdata% and let me know if there are any folders relating to fit launcher and if they contain files inside.
> 
> In local i see a `EBWebView` folder with other folders and some files. ![image](https://private-user-images.githubusercontent.com/74725303/363773164-9e888bcc-e396-4744-8694-9e9f61bc1906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMDMyNjgsIm5iZiI6MTcyNTMwMjk2OCwicGF0aCI6Ii83NDcyNTMwMy8zNjM3NzMxNjQtOWU4ODhiY2MtZTM5Ni00NzQ0LTg2OTQtOWU5ZjYxYmMxOTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE4NDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMDUxOGQzMDEwODhiOGQ1MzU1MDY4OTRkZmQ0MjUzNGVhNjhmMjBjM2RmNzdjN2ViZTMyNWI1Njk3ZTFhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pn78HZTi8nMEdPoSXl3SubjzPIVBMfkI-oQrxJYTAA8)
> 
> On Roaming nothing.
> 
> > 2. Are you able to turn on your VPN and run the app again?
> >    I think the VPN was the problem,  cause I didn't enable it when trying to run the app. Now it works!
> 
> P.S. I'm from Italy

Thank you for confirming. The issue was that your internet was blocking the connection to the server which was causing the app to hang / crash. 

We'll be sure to fix this by letting the app still open and alert the user that the servers were unreachable. 

@CarrotRub, this can be closed as it's fixed.

**Comment by CarrotRub** [comment] 2024-09-02 18:58
Thank you for fixing it :3 .

**Closed by CarrotRub** 2024-09-02 18:58 UTC
Labels: bug, help wanted

**Comment by InternetNinjo** [comment] 2024-12-27 12:21
> Thank you for fixing it :3 .

it's crashing again on Windows 11 23H2, no error reports
no event viewer entries, not sure what could be the cause

**Comment by CarrotRub** [comment] 2024-12-27 16:34
Have you tried the new 2.0 version ?
Have you ever tried to uninstall Microsoft Edge ?
What is your AV (antivirus) and have you tried disabling it ?

Please check if this fixes it, thank you.

**Comment by InternetNinjo** [comment] 2024-12-29 10:50
> Have you tried the new 2.0 version ? Have you ever tried to uninstall Microsoft Edge ? What is your AV (antivirus) and have you tried disabling it ?
> 
> Please check if this fixes it, thank you.

So it needs edge(webview2) to work? which i don't use

**Comment by InternetNinjo** [comment] 2024-12-29 10:54
> Have you tried the new 2.0 version ? Have you ever tried to uninstall Microsoft Edge ? What is your AV (antivirus) and have you tried disabling it ?
> 
> Please check if this fixes it, thank you.

I don't use AV(have deleted it)
and yes the 2.0.1 is working as intended

![Fit_Launcher_AhERx1YW8A](https://github.com/user-attachments/assets/8db0cf58-db4e-402a-9c70-5ea508fa6f3e)
but this is odd, the resolution supposed to be fit?

**Comment by CarrotRub** [comment] 2024-12-29 11:52
Nah I made it like that but I think now that I am seeing other resolutions it may be better to have a fixed res. 
Thank you.
