### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by BadBro00** [CarrotRub/Fit-Launcher#5] opened 2024-08-31 11:54 UTC
# The exe won't run

As soon as i downloaded the **msi** installer, i executed it, and set up the `.exe` Launcher in my `C:/Program Files/` folder, as recommended.

But, as soon as i ran the `.exe`, nothing happened.

**The app doesn't show up in the Task Manager at all**, so i assumed it wasn't running at all. I also tried running it as administrator, but nothing changed.

I also tried _re-installing_ it, but nothing changed. Maybe a problem with the msi installer?

## The folder only shows these two entries:
![FitLauncher](https://github.com/user-attachments/assets/322bb36d-54ea-4c04-b840-c5af98a6aa22)
---
I will also try the other installers, like the `.zip` archive, but it requires more work, so i'll update this issue when done with it.

# Hoping to get this fixed
See you later!

**Comment by devsheva** [comment] 2024-09-01 15:49
duplicate of #4

**Comment by KiraiEEE** [comment] 2024-09-01 18:15
on my device it showed rotating circle and looked like a legit malware so deleted it xD

**Comment by CarrotRub** [comment] 2024-09-01 21:54
Duplicate of #4

**Closed by CarrotRub** 2024-09-01 21:54 UTC
